hoistPattern:
  - '*'
hoistedDependencies: {}
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@6.32.10
pendingBuilds: []
prunedAt: Fri, 02 Jun 2023 15:03:31 GMT
publicHoistPattern:
  - '*'
registries:
  default: https://registry.npmjs.org/
skipped: []
storeDir: /home/workspace/.pnpm-store/v3
virtualStoreDir: .pnpm
